import { defineConfig, Options } from 'tsup'

export default defineConfig((options: Options) => ({
    entry: {
        index: 'cli.ts',
    },
    banner: {
        js: 'This file is generated by the Color Agent CLI. Do not edit it directly.',
    },
    clean: true,
    format: ['esm'],
    ...options,
}))
