const systemColorNames = [
    'accentcolor',
    'accentcolortext',
    'activetext',
    'buttonborder',
    'buttonface',
    'buttontext',
    'canvas',
    'canvastext',
    'field',
    'fieldtext',
    'graytext',
    'highlight',
    'highlighttext',
    'linktext',
    'mark',
    'marktext',
    'selecteditem',
    'selecteditemtext',
    'visitedtext',
    'activeborder',
    'activecaption',
    'appworkspace',
    'background',
    'buttonhighlight',
    'buttonshadow',
    'captiontext',
    'inactiveborder',
    'inactivecaption',
    'inactivecaptiontext',
    'infobackground',
    'infotext',
    'menu',
    'menutext',
    'scrollbar',
    'threeddarkshadow',
    'threedface',
    'threedhighlight',
    'threedlightshadow',
    'threedshadow',
    'window',
    'windowframe',
    'windowtext',
] as const
export type SystemColor = (typeof systemColorNames)[number]
export const systemColors = new Set(systemColorNames)
