export const TYPOGRAPHY_TOKENS = [
    'root',
    'display01',
    'display02',
    'display03',
    'display04',
    'h1',
    'h2',
    'h3',
    'h4',
    'h5',
    'h6',
    'cardTitle',
    'lead',
    'leadBold',
    'body',
    'bodyMedium',
    'bodySemiBold',
    'bodyBold',
    'bodySmall',
    'bodySmallMedium',
    'bodySmallSemiBold',
    'bodySmallBold',
    'bodyLarge',
    'bodyLargeMedium',
    'bodyLargeSemiBold',
    'bodyLargeBold',
    'detail',
    'detailMedium',
    'detailSemiBold',
    'detailBold',
    'label',
    'labelSmall',
    'linkText',
    'caption',
    'captionBold',
    'code',
    'codeBold',
    'address',
    'overline',
    'overlineSmall',
] as const

export type TypographyToken = (typeof TYPOGRAPHY_TOKENS)[number]
